import turtle
wn=turtle.Screen()
bob=turtle.Turtle()
wn.bgcolor("lightgreen")
bob.color("blue")
bob.pensize(2)
for i in range(20):
    bob.right(18)
    bob.forward(100)
    bob.backward(100)
    bob.forward(100)
    bob.right(90)
    bob.forward(100)
    bob.right(90)
    bob.forward(200)
    bob.right(90)
    bob.forward(200)
    bob.right(90)
    bob.forward(200)
    bob.right(90)
    bob.forward(100)
    bob.left(90)
    bob.backward(100)
©